-- MySQL Script generated by MySQL Workbench
-- Sat Mar 11 15:02:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CMA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CMA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CMA` DEFAULT CHARACTER SET utf8 ;
USE `CMA` ;

-- -----------------------------------------------------
-- Table `CMA`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(45) NULL,
  `updated_at` DATE NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `project_description` VARCHAR(45) NULL,
  `project_location` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`companies_has_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`companies_has_projects` (
  `companies_company_id` INT NOT NULL,
  `projects_project_id` INT NOT NULL,
  INDEX `fk_companies_has_projects_companies1_idx` (`companies_company_id` ASC),
  INDEX `fk_companies_has_projects_projects1_idx` (`projects_project_id` ASC),
  CONSTRAINT `fk_companies_has_projects_companies1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `CMA`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_projects_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `CMA`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`users_has_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`users_has_companies` (
  `users_user_id` INT NOT NULL,
  `companies_company_id` INT NOT NULL,
  INDEX `fk_users_has_companies_users1_idx` (`users_user_id` ASC),
  INDEX `fk_users_has_companies_companies1_idx` (`companies_company_id` ASC),
  CONSTRAINT `fk_users_has_companies_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `CMA`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_companies_companies1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `CMA`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`tasks` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NOT NULL,
  `projects_project_id` INT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `estimated_time` VARCHAR(45) NULL,
  PRIMARY KEY (`task_id`),
  INDEX `fk_tasks_projects1_idx` (`projects_project_id` ASC),
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `CMA`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`users_has_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`users_has_tasks` (
  `users_user_id` INT NOT NULL,
  `tasks_task_id` INT NOT NULL,
  INDEX `fk_users_has_tasks_users1_idx` (`users_user_id` ASC),
  INDEX `fk_users_has_tasks_tasks1_idx` (`tasks_task_id` ASC),
  CONSTRAINT `fk_users_has_tasks_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `CMA`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tasks_tasks1`
    FOREIGN KEY (`tasks_task_id`)
    REFERENCES `CMA`.`tasks` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`specialty` (
  `specialty_id` INT NOT NULL AUTO_INCREMENT,
  `specialty_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`specialty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`companies_has_specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`companies_has_specialty` (
  `specialty_specialty_id` INT NOT NULL,
  `companies_company_id` INT NOT NULL,
  INDEX `fk_companies_has_specialty_specialty1_idx` (`specialty_specialty_id` ASC),
  INDEX `fk_companies_has_specialty_companies1_idx` (`companies_company_id` ASC),
  CONSTRAINT `fk_companies_has_specialty_specialty1`
    FOREIGN KEY (`specialty_specialty_id`)
    REFERENCES `CMA`.`specialty` (`specialty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_specialty_companies1`
    FOREIGN KEY (`companies_company_id`)
    REFERENCES `CMA`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMA`.`users_has_specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMA`.`users_has_specialty` (
  `specialty_specialty_id` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  INDEX `fk_users_has_specialty_specialty1_idx` (`specialty_specialty_id` ASC),
  INDEX `fk_users_has_specialty_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_users_has_specialty_specialty1`
    FOREIGN KEY (`specialty_specialty_id`)
    REFERENCES `CMA`.`specialty` (`specialty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_specialty_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `CMA`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
